baseURL = 'https://notesbysmhd.ir/'
languageCode = 'fa-IR'
theme = 'hugo-theme-stack'
title = 'یادداشت‌های SMhd'
enableRobotsTXT = true

defaultContentLanguage = 'fa'
[languages]
  [languages.fa]
    languageName = 'فارسی'
    languageCode = 'fa-IR'
    languageDirection = 'rtl'
    weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1

[services]
  [services.googleAnalytics]
    id = 'G-Y85TL9NNSB'
