baseURL = 'https://example.org/'
languageCode = 'fa-IR'
theme = 'hugo-theme-stack'

defaultContentLanguage = 'fa'
[languages]
  [languages.fa]
    languageName = 'فارسی'
    languageCode = 'fa-IR'
    languageDirection = 'rtl'
    weight = 1
  [languages.en]
    languageName = 'English'
    weight = 2

[params]
  mainSections = 'posts'
  [params.sidebar]
    emoji = '⏳'
    [params.sidebar.avatar]
      src = 'notes-by-smhd.png'
