baseURL = 'https://notesbysmhd.ir/'
languageCode = 'fa-IR'
theme = 'hugo-theme-stack'
title = 'اس‌ام‌اچ‌دی می‌نویسد'

defaultContentLanguage = 'fa'
[languages]
  [languages.fa]
    languageName = 'فارسی'
    languageCode = 'fa-IR'
    languageDirection = 'rtl'
    weight = 1

[menus]
  [[main]]
    name = 'پست‌ها'
    pageRef = '/posts'
    weight = 1
  [[main]]
    name = 'دربارهٔ من'
    pageRef = '/about_me'
    weight = 2

[params]
  mainSections = 'posts'
  [params.sidebar]
    emoji = '⏳'
    [params.sidebar.avatar]
      src = 'notes-by-smhd.png'
