baseURL = 'https://notesbysmhd.ir/'
languageCode = 'fa-IR'
theme = 'hugo-theme-stack'
title = 'یادداشت‌های اس‌ام‌اچ‌دی'

defaultContentLanguage = 'fa'
[languages]
  [languages.fa]
    languageName = 'فارسی'
    languageCode = 'fa-IR'
    languageDirection = 'rtl'
    weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1