mainSections = ['posts']
[sidebar]
  emoji = '⏳'
  [sidebar.avatar]
    src = 'notes-by-smhd.png'
[article]
  toc = true
[widgets]
  [[widgets.page]]
    type = 'toc'
  [[widgets.homepage]]
    [[widgets.homepage]]
      type = 'archives'
    [[widgets.homepage]]
      type = 'categories'
      [widgets.homepage.params]
        limit = 10
    [[widgets.homepage]]
      type = 'tag-cloud'
      [widgets.homepage.params]
        limit = 10
[footer]
  since = 2025