mainSections = ['posts']

[sidebar]
  emoji = '⏳'
  subtitle = 'اندر خم مینیمالیسم، بهره‌وری و کد'
  [sidebar.avatar]
    src = 'notes-by-smhd.png'

[article]
  toc = true

[opengraph]
  [opengraph.twitter]
    site = 'SMhdAsadi'
    card = 'summary_large_image'

[comments]
  enabled = true
  provider = 'giscus'
  [comments.giscus]
    repo = 'SMhdAsadi/notes-by-smhd'
    repoID = 'R_kgDONyTXYg'
    category = 'Announcements'
    categoryID = 'DIC_kwDONyTXYs4Cmvcj'
    mapping = 'pathname'
    strict = 0
    lightTheme = 'preferred_color_scheme'
    darkTheme = 'preferred_color_scheme'
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = 'top'
    lang = 'fa'
    crossOrigin = 'anonymous'
    async = true

[widgets]
  [[widgets.page]]
    type = 'toc'
  [[widgets.homepage]]
    [[widgets.homepage]]
        type = 'search'
    [[widgets.homepage]]
      type = 'archives'
    [[widgets.homepage]]
      type = 'categories'
      [widgets.homepage.params]
        limit = 10
    [[widgets.homepage]]
      type = 'tag-cloud'
      [widgets.homepage.params]
        limit = 10

[footer]
  since = 2025